version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/modules/abbreviations"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/cosmos_db"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/function_app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/storage_account"
    schedule:
      interval: "weekly"
